### ISSUE TITLE
입출국 승인 페이지 및 목록 조회 페이지 javaFX 적용

### ISSUE THREAD

**Issue by ssooyaa** [SysWin1/OneStepOneStamp#18]
## 💼 작업 설명

입출국 관련 서비스 페이지 JavaFX적용

## ✅ To-do

- [ ] 입출국 승인 페이지 만들기
- [ ] 입출국 목록 조회 페이지 만들기
- [ ] 입출국 서비스 로직 테스트
