### ISSUE TITLE
자동 출입국 신청서 입력(JAVA) 및 DB 연결

### ISSUE THREAD

**Issue by HJunng** [SysWin1/OneStepOneStamp#2]
## 💼 작업 설명

신청서 입력 java <-> oracle procedure insert 처리 완료

[클래스 분리]
- DAO : 직접 DB와 소통
- Service : 비즈니스 로직 적용 (값 받아와서, 신청번호, 신청일자 추가)
- UUIDShortener : uuid값을 짧게 줄인 클래스

## ✅ To-do

- [x] Oracle에 `신청서 입력 procedure` 생성
- [x] DB - JAVA 연결
- [x] CallableStatement 사용해서 sql문 작성
- [x] java 내의 더미값 1개 넣어서 테스트 완료
