### ISSUE TITLE
[JavaFX] 사용자 - 자동 입출국 신청 목록 조회

### ISSUE THREAD

**Issue by HJunng** [SysWin1/OneStepOneStamp#21]
## 💼 작업 설명

자동 입출국 신청 목록 조회
(여권번호, 국적)을 사용해서 조회

## ✅ To-do

- [x] 의존성 추가
- [x] 사용자 - 자동 입출국 신청서 목록 조회
- [x] select sql 쿼리문 작성
- [x] JavaFX에서 TableView로 컬럼 넣어서 리스트로 view 조회
