### ISSUE TITLE
외국인 입국 승인처리 로직 구상 및 프로시저 작성

### ISSUE THREAD

**Issue by dabeen-jung** [SysWin1/OneStepOneStamp#22]
## 💼 작업 설명

외국인 입국 승인처리 로직 구상 및 프로시저 작성
더미데이터로 로직 테스트

✅ To-do

 더미데이터 생성
 로직 테스트

## ✅ To-do

- [x] 외국인 입국 승인처리 로직 구상
- [x] 외국인 입국 승인처리 프로시저 작성
- [x] 더미데이터로 프로시저 테스트
- [x] 트리거 작동테스트
