### ISSUE TITLE
각 프로시저 로직 검증 및 테스트 

### ISSUE THREAD

**Issue by dabeen-jung** [SysWin1/OneStepOneStamp#27]
## 💼 작업 설명

각 프로시저 로직 검증 및 테스트 

## ✅ To-do

- [x] 외국인 입국 심사’ 프로시저 로직 검증
    - [x]  더미 데이터 삽입 및 테스트
- [x]  ‘외국인 출국 심사’  프로시저 로직 검증
    - [x]  더미 데이터 삽입 및 테스트 작업
- [x]  ‘내국인 입국 심사’ 프로시저 로직 검증
