### ISSUE TITLE
JavaFX 스타일 수정 및 코드 리팩토링

### ISSUE THREAD

**Issue by ssooyaa** [SysWin1/OneStepOneStamp#33]
## 💼 작업 설명

javaFX  전체 스타일 수정
서비스 로직 코드 리팩토링

## ✅ To-do

- [ ] JavaFX 팝업 아이콘 수정
- [ ] view 문구 수정
- [ ] 서비스 로직 리팩토링
