### ISSUE TITLE
[JavaFX] 유저 메인 페이지 fxml 변환 후 css 적용

### ISSUE THREAD

**Issue by HJunng** [SysWin1/OneStepOneStamp#47]
## 💼 작업 설명

유저 메인 페이지를 기본 페이지로 변경
유저 메인 페이지를 fxml로 변경, css 적용

## ✅ To-do

- [ ] 메인 페이지 fxml 변환
- [ ] css 적용
- [ ] 유저 메인 페이지를 메인 페이지로 적용
- [ ] 자동 출입국 신청서 작성 페이지를 fxml로 변경
