### ISSUE TITLE
심사 및 자격관리(내국인-입국) 로직 개발 및 DB 연결

### ISSUE THREAD

**Issue by dabeen-jung** [SysWin1/OneStepOneStamp#5]
## 💼 작업 설명

출입국 심사 및 자격관리 트리거 틀 생성
내국인 입국 승인처리 로직 작성(PL/SQL 함수)

## ✅ To-do

- [x] 더미 데이터 생성
- [x] db-jdbc 연결
- [x] 심사 및 자격관리 트리거 틀 생성
- [x] 내국인 입국 승인처리 함수 로직 작성
